pipeline{
    agent{
        label "nodejs"
    }
    stages{
        stage('Deploy') {
            steps {
             sh '''
             oc project zrghfg-deploy-strategies
             oc start-build greeting-service --follow --wait
            '''
            }
        }
    }
}
